apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: my-flask-app  # Must match the Deployment's pod label
  ports:
    - protocol: TCP
      port: 80          # Service port (inside cluster)
      targetPort: 5000  # Flask app port inside the pod
      nodePort: 30000   # Exposed port on the Node (for external access)
  type: NodePort         # Type of service to expose to external traffic
